apiVersion: apps/v1
kind: Deployment
metadata:
  name: attestation-admission-controller
  namespace: default
  labels:
    app: attestation-admission-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attestation-admission-controller
  template:
    metadata:
      labels:
        app: attestation-admission-controller
    spec:
      containers:
      - name: webhook
        image: attestation-admission-controller:latest
        imagePullPolicy: Never  # Use local image built with minikube docker
        ports:
        - containerPort: 8443
          name: webhook-api
        volumeMounts:
        - name: webhook-certs
          mountPath: /certs
          readOnly: true
        env:
        - name: TLS_CERT_FILE
          value: /certs/tls.crt
        - name: TLS_PRIVATE_KEY_FILE
          value: /certs/tls.key
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 64Mi
            cpu: 50m
        livenessProbe:
          httpGet:
            path: /health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: webhook-certs
      securityContext:
        fsGroup: 1000
